version: '3'

services:
  app:
    build: .
    image: eclipse-temurin:17-jdk-alpine
    ports:
      - "8080:8080"
    links:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fp065_db
      MYSQL_USER: user
      MYSQL_PASSWORD: '1234'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: '3306'
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  mysql-data:
